default: &default
  host: ''
  adapter: postgresql
  encoding: unicode
  database: ttt
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: ttt_development

test:
  <<: *default
  database: ttt_test

production:
  <<: *default
  database: ttt_production